config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "top#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /ja|en/ do
    resources :users, only: [:show, :following, :followers] do
      member { get :following, :followers }
    end
    resources :relationships, only: [:create, :destroy]

    resources :books do
      resources :comments, only: [:create, :edit, :destroy, :update], module: :books
    end

    resources :reports do
      resources :comments, only: [:create, :edit, :destroy, :update], module: :reports
    end
  end
end

app/views/shared/_header.html.erb
<header>
  <% if I18n.locale.to_s == "en" %>
    <%= link_to('日本語サイト', :locale => 'ja') %>
    <% else %>
    <%= link_to('English site', :locale => 'en') %>
  <% end %>

  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      <strong><%= current_user.username %></strong>
      <%= t('.log_in_now') %></br>
    <% end %>
    <%= link_to t('.home'), root_path, class: 'navbar-link' %> |
    <%= link_to t('.books'), books_path, class: 'navbar-link' %> |
    <%= link_to t('.reports'), reports_path, class: 'navbar-link' %> |
    <% if user_signed_in? %>
      <%= link_to t('.profile'), current_user, class: 'navbar-link' %> |
      <%= link_to t('.edit_profile'), edit_user_registration_path, class: 'navbar-link' %> |
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
    <% else %>
      <%= link_to t('.sign_up'), new_user_registration_path, class: 'navbar-link'  %> |
      <%= link_to t('.sign_in'), new_user_session_path, class: 'navbar-link'  %>
    <% end %>
  </p>
</header>

app/views/shared/_stats.html.erb
<% user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(user) %>">
    <strong id="following" class="stat">
      <%= user.following.count %>
    </strong>
    <%= t('.following') %>
  </a>
  <a href="<%= followers_user_path(user) %>">
    <strong id="followers" class="stat">
      <%= user.followers.count %>
    </strong>
    <%= t('.followers') %>
  </a>
</div>