config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "top#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /ja|en/ do
    resources :users, only: [:show, :following, :followers] do
      member { get :following, :followers }
    end
    resources :relationships, only: [:create, :destroy]

    resources :books do
      resources :comments, only: [:create, :edit, :destroy, :update], module: :books
    end

    resources :reports do
      resources :comments, only: [:create, :edit, :destroy, :update], module: :reports
    end
  end
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
end

app/controllers/reports/comments_controller.rb
# frozen_string_literal: true

class Reports::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Report.find(params[:report_id])
    end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  include ResourceSetter

  before_action :set_resource, only: [:show]
  before_action :set_my_resource, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

  NUMBER_PER_PAGE = 10

  # GET /reports
  def index
    @reports = Report.page(params[:page]).per(NUMBER_PER_PAGE)
  end

  # GET /reports/1
  def show
    @user = User.find(@report.user_id)
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  def create
    @report = current_user.reports.new(report_params)
    if @report.save
      redirect_to @report, notice: t("notice.create")
    else
      render :new
    end
  end

  # PATCH/PUT /reports/1
  def update
    if @report.update(report_params)
      redirect_to @report, notice: t("notice.update")
    else
      render :edit
    end
  end

  # DELETE /reports/1
  def destroy
    if @report.destroy
      redirect_to reports_url, notice: t("notice.destroy")
    else
      redirect_to reports_url
    end
  end

  private
    def report_params
      params.require(:report).permit(:title, :body)
    end
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1><%= t('.editing_report') %></h1>

<%= render 'form', report: @report %>

<%= link_to t('link.back'), :back %> |
<%= link_to t('link.destroy'), @report, method: :delete, data: { confirm: t('confirm') } %>

app/views/reports/index.html.erb
<h1><%= Report.model_name.human %></h1>

<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name :username %></th>
      <th><%= Report.human_attribute_name :title %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= link_to report.user.username, report.user, class: 'navbar-link' %></td>
        <td><%= link_to report.title, report_path(report), class: 'navbar-link' %></td>
        <% if report.user == current_user %>
          <td><%= link_to t('link.edit'), edit_report_path(report) %></td>
          <td><%= link_to t('link.destroy'), report, method: :delete, data: { confirm: t('confirm') } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('link.new_report'), new_report_path %>

<div class='paginate'><%= paginate @reports %><div>

app/views/reports/new.html.erb
<h1><%= t('.new_report') %></h1>

<%= render 'form', report: @report %>

<%= link_to t('link.go_to_reports'), reports_path %>

app/views/reports/show.html.erb
<div class="report_content">
  <h1><%= t('.report_information') %></h1>

  <h3><%= @report.title %></h3>

  <p>
    <%= User.human_attribute_name :username %>:
    <%= link_to @user.username, @user %>
  </p>
  <p><%= @report.body %></p>
  <% if @report.user == current_user %>
    <p>
    <%= link_to t('link.edit'), edit_report_path(@report) %>
    <%= link_to t('link.destroy'), @report, method: :delete, data: { confirm: t('confirm') } %>
    </p>
  <% end %>

  <p><%= link_to t('link.go_to_reports'), reports_path %></p>
</div>

<%= render partial: "comments/comment", locals: {commentable: @report} %>
<% if user_signed_in? %>
  <%= render partial: "comments/form", locals: {commentable: @report, comment: Comment.new} %>
<% end %>

<%= link_to t('link.go_to_reports'), reports_path %>